APP_STL := c++_static
NDK_TOOLCHAIN_VERSION=clang
APP_CPPFLAGS := -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DCOCOS2D_DEBUG=1 -DCC_FIX_ARTIFACTS_BY_STRECHING_TEXEL=1 -std=c++11 -fsigned-char

APP_LDFLAGS := -latomic

